addons:
  apt:
    packages:
    - unzip
    - mcpp
language: generic
branches:
  except:
  - "/^travis_ok-*.$/"
before_script:
- wget https://github.com/Makopo/lslint/releases/download/v1.0.8/lslint_v1.0.8_linux.zip -O lslint.zip
- unzip lslint.zip

script:
- mkdir -p compiled
- mcpp -P "Kemono-Body-Script.lsl" > compiled/xenhat.kemono.body.lsl
- "./lslint -m -i < compiled/xenhat.kemono.body.lsl"
env:
  global:
    - secure: SwvbDpU3dle++rBnflUEJqkBwskinn8Hctn+BvitwGOKvDlnfOWCcHeY6YH4U71XCwuK9ix/OwZ37GbAs8vU3pdzXguMSnHlPXUcyxBh4qHMCeeO6QA453hcV35x0vhE+rrbxMYDpXImFdtEwGJfznaqI6hwuqHw/1m9InjavYBBLG7OHwfILI3Zo4gCLgNAJKzOvMOVoYHCqCzyqVWBlKgHDp2vRiD4jn08ciFbJJmqg4igj2v5+rkXEyIu8bSgssHlw75sNJqrlEZDlrP7fIIXnJIknMmgfYgW43N2YHFGZReSAYn15AzVGKpQC5DCzzLX98KqrNminWJkGm2LTJ3yNnA7vPZH1maKM5d3vbn4eSMx2MBzj+bd2JQQZyQhkCIJLWtBCwnFvQMApoHJWrJC8a0RkgfObWhHp7tDHAhXMedqkY5k9autGmnXh0/Ep7UeAlzae+x5u5RonUewOQhksdDFZEHJqxTi3up9JokKOMeqvl0JfRZxX+MvXrD6YUqdBbaCFmZ4CSPoncr8Liw+04m3uwJWh4GrspEYq6KqGhXC/NWTstIwcmQMtJ0y2YV7e9M6wZ5xsR5w1W39LXUUbuzeYf68HZR14IXTEvCGFMlYRKj9XiGhztlD6avTnkUUDXz9GetqSUKwZxw6RF3KkvmJBrXh/B7+Nsbk4Sw=

after_success:
- git config credential.helper "store --file=.git/credentials"
- echo "https://${GH_TOKEN}:@github.com" > .git/credentials
- git tag | grep travis | xargs -n 1 -i% git push origin :refs/tags/%
- git add compiled/xenhat.kemono.body.lsl
- bash ./travis-ci-git-commit.bash
deploy:
  provider: releases
  # description: "Automated Release"
  # release: "Release build $TRAVIS_BUILD_NUMBER"
  # tag: "travis_ok"

  file: compiled/xenhat.kemono.body.lsl
  skip_cleanup: true
  on:
    repo: XenHat/Kemono-Body-Script
    tags: true
    # condition: "$TRAVIS_TAG =~ ^\d.\d.\d$"
    condition: "$TRAVIS_TAG =~ ^travis_ok-.*$"
