language: generic
branches:
  except:
  - "/^travis_ok-*.$/"
before_script:
- sudo apt-get -qq update
- sudo apt-get install -y unzip mcpp
- wget https://github.com/Makopo/lslint/releases/download/v1.0.6/lslint_v1.0.6_linux.zip
- unzip lslint_v1.0.6_linux.zip
script:
- mcpp -P "Kemono-Body-Script.lsl" > compiled/xenhat.kemono.body.lsl && ./lslint -m -i
  < compiled/xenhat.kemono.body.lsl
- git config credential.helper "store --file=.git/credentials"
- echo "https://${GH_TOKEN}:@github.com" > .git/credentials
after_success:
- bash ./travis-ci-git-commit.bash
deploy:
  provider: releases
  # description: "Automated Release"
  # release: "Release build $TRAVIS_BUILD_NUMBER"
  # tag: "travis_ok"
  api_key:
    secure: ZRBHhuU2CJP1kX68m8eYDU8ZlCsyQ/c8aNGNRFeIhXoNyDhlssx1X70OfDE0hwz5LsvabtywDaXUldBqSmSwoq5hqQ0U0lvz2NuPx+xPNojBg+Gf/rdaeoYDv9fwAukOxeBisjPzGEgd0b00FwCm9S8zbleZACKs7r2GKXqgMaQ4tqAfcq7aAJc8Whsy1ja0quf1nzuAJtCq8Tl39n4Id996l3+hYFB4XrSn4X6WAE45DP/Xxr/FMaED9X/Utyad4xtg3CmeR2yZ92AlQGXciwHgJXVPDrBtanl29cYRf8Mwkc2suH4I4V7kUOTc985qoFORhinX9I1CUyjZ0n2P0FRw2bVbp8HWvml6GqlD0MkCXTjPQUQlqltyS9xjq0F0tZph/BXgXDPq5uRUYoqk4h7RppKG6awOQYmYrLV7pHUHBwJIS9IsPXaIJCZG0zhSWP4iy/r8WjaBCjNBTCc7VNAPMPb6D+XWwPGHN2JFTAQCWYDPFzKr8NQFjq037SOFOZfp8xHqp6yZZ2W5M0iKDCtufDQbeIng0s6wxBCjoxCe/uIYzQT/GuryOVlJhKTIM6wYUvMXcY+nSD35LPcx4hvuGiJKCph/WgL+6HxaGpdBhwTTgvlL2+vVugT0MuCNf78WMzaRISRz/sR0X+TNUxhIC4JHa+rQn8fJ+8455cs=
  file: compiled/xenhat.kemono.body.lsl
  skip_cleanup: true
  on:
    repo: XenHat/Kemono-Body-Script
    tags: true
    # condition: "$TRAVIS_TAG =~ ^\d.\d.\d$"
    condition: "$TRAVIS_TAG =~ ^travis_ok-.*$"
